services:
  api:
    container_name: prayhelper-client-dev
    build:
      context: .
      dockerfile: Dockerfile
    image: prayhelper-client-dev
    ports:
      - "4001:3000"
    command: ["serve", "-s", "build"]
