services:
  api:
    container_name: uspray-client-intg
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    image: registry.uspray.kr/uspray-client-intg:latest
    ports:
      - "4005:3000"
    command: ["serve", "-s", "build"]
    env_file:
      - .env