name: Deploy frontend on Production Server

on:
  release:
    types:
      - published

env:
  HOST:     ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  KEY:      ${{ secrets.SSH_KEY }}
  PORT:     ${{ secrets.PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Decrypt environment variables
        run: |
          echo "${{ secrets.ENV }}" base64 -d > .env        


      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: registry.uspray.kr/uspray-client-prod:latest

      - name: Aquire Lock
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          script: |
            while [ -f ~/SEMAPHORE ]; do sleep 10; done
            touch ~/SEMAPHORE

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          script: |
            cd ~/frontend-prod
            docker stop uspray-client-prod
            docker rm uspray-client-prod
            docker rmi registry.uspray.kr/uspray-client-prod:latest
            docker run -d --name uspray-client-prod -p 4003:3000 --env-file .env registry.uspray.kr/uspray-client-prod:latest

      - name: Release Lock
        if: always()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          script: |
            rm ~/SEMAPHORE