name: Deploy Frontend on Integration Server

on:
  push:
    branches:
      - feature/**
      - feat/**

env:
  HOST:     ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  KEY:      ${{ secrets.SSH_KEY }}
  PORT:     ${{ secrets.PORT }}
  INSTANCE_PATH: ./frontend-intg

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == vars.INTG_BRANCH
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: registry.uspray.kr/uspray-intg:latest

      - name: Aquire Lock
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          script: |
            while [ -f ~/SEMAPHORE_FILE ]; do sleep 10; done
            touch ~/SEMAPHORE_FILE

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          script: |
            cd ${{ env.INSTANCE_PATH }}
            make build-intg

      - name: Release Lock
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          script: |
            rm ~/SEMAPHORE_FILE