name: Deploy Frontend on Integration Server

on:
  push:
    branches:
      - feature/**
      - feat/**

env:
  HOST:     ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  KEY:      ${{ secrets.SSH_KEY }}
  PORT:     ${{ secrets.PORT }}
  INSTANCE_PATH: ./frontend-intg

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print INTG_BRANCH
      run: echo "INTG_BRANCH is ${{ vars.INTG_BRANCH }}"

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 19

    - name: Install dependencies
      run: |
        npm config set legacy-peer-deps true
        npm ci

    - name: Run tests
      run: |
        CI=false
        npm test

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == format('refs/heads/{0}', vars.INTG_BRANCH)
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: registry.uspray.kr/uspray-intg:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ env.KEY }}
          port: ${{ env.PORT }}
          script: |
            cd ${{ env.INSTANCE_PATH }}
            make build-intg