name: Deploy Frontend on Dev Server
on:
  push:
    branches:
      - feature/cd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: |
            ./package.json
            ./package-lock.json
            ./src/
            ./public/
          target: "/home/prayhelper/prayhelper-frontend"
          args: -r

      - name: Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/prayhelper/prayhelper-frontend
            ./run.sh
