name: Deploy Frontend on Development Environment

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - deploy/v2-workflow

env:
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  KEY: ${{ secrets.SSH_KEY }}
  PORT: ${{ secrets.PORT }}
  IMAGE_NAME: registry.uspray.kr/uspray-client-dev:latest
  PROJECT_NAME: uspray-client-dev
  DOMAIN_HOST: www.dev.uspray.kr

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Decrypt environment variables
        run: |
          echo "${{ secrets.DEV_ENV }}" base64 -d > .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./deploy/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}
          platforms: linux/amd64

  deploy:
    needs: deliver
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Docker image
        env:
          SERVICE_NAME: ${{ env.PROJECT_NAME }}
          DOMAIN_HOST: ${{ env.DOMAIN_HOST }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: |
          if [ ! -z "$(docker ps -q -f name=${{env.PROJECT_NAME}})" ]; then
            docker compose -f ./deploy/docker-compose.yml -p ${{env.PROJECT_NAME}} down
            docker rmi ${{env.IMAGE_NAME}}
          fi
          docker compose -f ./deploy/docker-compose.yml -p ${{env.PROJECT_NAME}} up -d
