name: Deploy Frontend on Integration Server

on:
  push:
    branches:
      - feature/**
      - feat/**

env:
  HOST:     ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}
  KEY:      ${{ secrets.SSH_KEY }}
  PORT:     ${{ secrets.PORT }}
  PATH:     ~/frontend-intg

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "test is skipped"
          echo $PATH

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/${{ vars.INTG_BRANCH }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send
        uses: appleboy/scp-action@master
        with:
          host: $HOST
          username: $USERNAME
          key: $KEY
          port: $PORT
          source: "."
          target: $PATH

      - name: Deploy 
        uses: appleboy/ssh-action@master
        with:
          host: $HOST
          username: $USERNAME
          key: $KEY
          port: $PORT
          script: |
            cd $PATH
            make build-intg
